### PR TITLE
[#42] Fix TestLedgerBackup unit test

### LINKED ISSUE #42: Fix TestLedgerBackup unit test

### PR DESCRIPTION
**Pull request by fqutishat**
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

closes #42

### CODE REVIEW

**Comment by fqutishat** [comment]
verify

File: core/ledger/kvledger/kv_ledger_provider_test.go [hunk 1]
```diff
@@ -214,7 +214,7 @@ func TestLedgerBackup(t *testing.T) {
 	provider.Close()
 
 	// Create restore environment
-	env := createTestEnv(t, restorePath)
+	env := createTestEnvWithoutSetupExtTestEnv(t, restorePath)
```
Comment (troyronda) [inline core/ledger/kvledger/kv_ledger_provider_test.go]: Perhaps some context on why this change is needed would help.

Comment (sudeshrshetty) [reply core/ledger/kvledger/kv_ledger_provider_test.go]: this is needed for "Initializing ledger provider", otherwise kvledger.NewProvider() will get stuck waiting for couchdb connection
